# Generated by Django 3.2.8 on 2021-10-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211026_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='_products_count',
            field=models.PositiveIntegerField(default=0, verbose_name='количество товаров'),
        ),
    ]
